## Cluster Settings
cluster.name: stac-cluster
node.name: es01
network.host: 0.0.0.0
transport.host: 0.0.0.0
discovery.type: single-node


# http
http.port: 9200
transport.tcp.compress: true
http.compression: true
http.compression_level: 3

path:
  repo:
    - /usr/share/elasticsearch/snapshots

## License
xpack.license.self_generated.type: basic

# Security
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false

# memory
bootstrap.memory_lock: true

# thread pool
thread_pool.search.size: 32 #default 3* Cores
thread_pool.search.queue_size: 1000 # 1000
#thread_pool.write.queue_size: 10000 # 1000

# index
indices.breaker.total.limit: 85%
indices.queries.cache.size: 20%  # Percentage of heap memory
indices.queries.cache.count: 100000  # Maximum number of cached queries